server:
  port: 8700

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

articles:
  random:
    title: 5
    text:
      min: 1
      max: 3

spring:
  jackson:
    serialization: 
      indent-output: true

---
spring:
  profiles: secondary

server:
  port: 8800

articles:
  random:
    title: 3