server:
  port: 8701

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  
news:
  top:
    defaultSize: 10

spring:
  jackson:
    serialization: 
      indent-output: true

